package ashina.carrental.entities.concretes;

import ashina.carrental.entities.concretes.users.Employee;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.OnDelete;

import java.util.ArrayList;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "job")
public class Job {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    // Title of the job
    @Column(name = "title")
    private String title;

    // Constructors, getters, setters, toString, equals, and hashCode are generated by Lombok.
    // Additional methods and logic can be added here.
    @OneToMany
    private List<Employee> employees=new ArrayList<>();
    
}
