package ashina.carrental.entities.concretes.users;

import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@PrimaryKeyJoinColumn(name = "users_id", referencedColumnName = "id")
@EqualsAndHashCode(callSuper = true)
@Table(name = "employees")
public class Employees extends Users {
    // This class represents the Users entity, which maps to the "users" table in the database

    @Column(name = "employee_number")
    private UUID employeeNumber;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "national_identification_number")
    private String nationalIdentificationNumber;

    @Column(name = "phone_number")
    private String phoneNumber;

    // Getters and setters are automatically generated by Lombok's @Data annotation
    // Lombok also generates the toString(), equals(), and hashCode() methods

}
