package ashina.carrental.entities.concretes.users;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "users")
public class Users {
    // This class represents the Users entity, which maps to the "users" table in the database
    

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id; // The primary key field for the user ID

    @Column(name = "email")
    private String email; // The email field for the user

    @Column(name = "password")
    private String password; // The password field for the user

    // Getters and setters are automatically generated by Lombok's @Data annotation
    // Lombok also generates the toString(), equals(), and hashCode() methods

}
